FROM nginx:latest

# Install Certbot and dependencies
RUN apt-get update && apt-get install -y certbot python3-certbot-nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Default Nginx setup
COPY nginx.conf /etc/nginx/conf.d/default.conf
