# Generated by Django 4.2.4 on 2023-08-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('spending_catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.spending_catergory')),
            ],
        ),
        migrations.CreateModel(
            name='Debt_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.debt')),
            ],
        ),
    ]
