# Generated by Django 4.2.4 on 2023-08-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_debt_income_savings_spending_debt_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending_catergory',
            name='remaingin_budget',
        ),
    ]
