# Generated by Django 4.2.4 on 2023-08-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_spending_catergory_remaingin_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='spending_catergory',
            new_name='spending_category',
        ),
    ]
