# Generated by Django 4.2.4 on 2023-08-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_spending_catergory_spending_spending_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending_catergory',
            old_name='spending_catergory',
            new_name='spending_category',
        ),
    ]
