# Generated by Django 4.2.4 on 2023-08-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_spending_catergory_spending_catergory_spending_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spending_Catergory',
            new_name='Spending_Category',
        ),
    ]
