# Generated by Django 4.2.4 on 2023-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_spending_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_account',
            field=models.CharField(default='debt', max_length=200),
            preserve_default=False,
        ),
    ]
