# Generated by Django 4.2.4 on 2023-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_debt_user_savings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='savings_account',
            field=models.CharField(default='Savings', max_length=200),
        ),
    ]
