# Generated by Django 5.0.1 on 2024-02-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
